Layout:
  Border:
    Free: BROWN_STAINED_GLASS_PANE
    Flawless: BROWN_STAINED_GLASS_PANE
    Chaotic: BROWN_STAINED_GLASS_PANE
  Tier:
    Free: PINK_STAINED_GLASS_PANE
    Flawless: PINK_STAINED_GLASS_PANE
    Chaotic: PINK_STAINED_GLASS_PANE
Buttons:
  Back: RED_GLAZED_TERRACOTTA
  Next_page: MAGENTA_GLAZED_TERRACOTTA
  Claim: LIME_DYE
  Exit: RED_DYE
Reward: GOLDEN_CARROT